-- Add up migration script here
BEGIN;

INSERT INTO
    services (
        id,
        name,
        exchange,
        queue,
        routing_key,
        cache_fields,
        timeout,
        cache_expiration
    )
VALUES
    (
        0,
        'Multi',
        'multi',
        'multi.q.request',
        'multi.q.request',
        '',
        35,
        '5d'
    ),
    (
        1,
        'Seon Phone',
        'seon_phone',
        'seon_phone.q.request',
        'seon_phone.q.request',
        'client_phone',
        20,
        '5d'
    ),
    (
        2,
        'Scorely',
        'scorely',
        'scorely.q.request',
        'scorely.q.request',
        'document_number,first_name,last_name,middle_name',
        15,
        '5d'
    ),
    (
        3,
        'Smartdata',
        'smartdata',
        'smartdata.q.request',
        'smartdata.q.request',
        'client_phone',
        15,
        '14d'
    ),
    (
        4,
        'Infosfera',
        'infosfera',
        'infosfera.q.request',
        'infosfera.q.request',
        'client_phone,sources,rules,system_id',
        30,
        '30d'
    ),
    (
        5,
        'Kalapa Antifraud',
        'kalapa_antifraud',
        'kalapa_antifraud.q.request',
        'kalapa_antifraud.q.request',
        'client_phone,id_number_vn, refer_time',
        20,
        '5d'
    ),
    (
        6,
        'Kalapa Scoring',
        'kalapa_scoring',
        'kalapa_scoring.q.request',
        'kalapa_scoring.q.request',
        'client_phone,id_number_vn, refer_time',
        20,
        '5d'
    ),
    (
        7,
        'IQID',
        'iqid',
        'iqid.q.request',
        'iqid.q.request',
        'client_phone',
        15,
        '14d'
    ),
    (
        8,
        'VK',
        'vk',
        'vk.q.request',
        'vk.q.request',
        'client_phone,models',
        20,
        '14d'
    ),
    (
        9,
        'Verifio Bankruptcy',
        'verifio_bankruptcy',
        'verifio_bankruptcy.q.request',
        'verifio_bankruptcy.q.request',
        'inn',
        10,
        '30d'
    ),
    (
        10,
        'Verifio Inn',
        'verifio_inn',
        'verifio_inn.q.request',
        'verifio_inn.q.request',
        'passport_series,passport_number',
        20,
        '30d'
    ),
    (
        11,
        'MFM',
        'mfm',
        'mfm.q.request',
        'mfm.q.request',
        'client_phone',
        10,
        '14d'
    ),
    (
        12,
        'Juicy Score',
        'juicy-score',
        'juicy-score.q.request',
        'juicy-score.q.request',
        'client_phone,email',
        15,
        '14d'
    ),
    (
        13,
        'Seon Email',
        'seon_email',
        'seon_email.q.request',
        'seon_email.q.request',
        'client_email',
        20,
        '5d'
    ),
    (
        14,
        'LGC',
        'lgc',
        'lgc.q.request',
        'lgc.q.request',
        'client_phone,client_client_id,client_birthday',
        20,
        '5d'
    ),
    (
        15,
        'Verifio Passport',
        'verifio_passport',
        'verifio_passport.q.request',
        'verifio_passport.q.request',
        'passport_series,passport_number,first_name,last_name',
        15,
        '1d'
    ),
    (
        16,
        'One Factor',
        'onefactor',
        'onefactor.q.request',
        'onefactor.q.request',
        'client_phone',
        10,
        '30d'
    ),
    (
        17,
        'Seon IP',
        'seon_ip',
        'seon_ip.q.request',
        'seon_ip.q.request',
        'client_ip',
        20,
        '5d'
    ),
    (
        18,
        'Megafon',
        'megafon',
        'megafon.q.request',
        'megafon.q.request',
        'client_phone',
        10,
        '30d'
    ),
    (
        19,
        'Fincard',
        'fincard',
        'fincard.q.request',
        'fincard.q.request',
        '',
        20,
        ''
    ),
    (
        20,
        'Equifax Scoring',
        'equifax_scoring',
        'equifax_scoring.q.request',
        'equifax_scoring.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        20,
        '14d'
    ),
    (
        21,
        'NSPK',
        'nspk',
        'nspk.q.request',
        'nspk.q.request',
        'client_phone',
        20,
        '14d'
    ),
    (
        22,
        'NBKI AFS',
        'nbki_afs',
        'nbki_afs.q.request',
        'nbki_afs.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        15,
        '14d'
    ),
    (
        23,
        'OKB Scoring',
        'okb_scoring',
        'okb_scoring.q.request',
        'okb_scoring.q.request',
        'client_phone',
        10,
        '14d'
    ),
    (
        24,
        'OKB UCH',
        'okb_uch',
        'okb_uch.q.request',
        'okb_uch.q.request',
        'first_name,last_name,middle_name,birthdate,passport_series,passport_number,system_id',
        20,
        '14d'
    ),
    (
        25,
        'FSSP',
        'fssp',
        'fssp.q.request',
        'fssp.q.request',
        '',
        10,
        ''
    ),
    (
        26,
        'Nubarium CURP',
        'nubarium_curp',
        'nubarium_curp.q.request',
        'nubarium_curp.q.request',
        'curp',
        30,
        '30d'
    ),
    (
        27,
        'Equifax V4',
        'equifax_v4',
        'equifax_v4.q.request',
        'equifax_v4.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        20,
        '5d'
    ),
    (
        28,
        'Nubarium INE',
        'nubarium_ine',
        'nubarium_ine.q.request',
        'nubarium_ine.q.request',
        'cic,identificadorCiudadano,ocr,claveElector,numeroEmision',
        30,
        '30d'
    ),
    (
        29,
        'Credit Circle',
        'credit_circle',
        'credit_circle.q.request',
        'credit_circle.q.request',
        'CURP,RFC',
        900,
        '30d'
    ),
    (
        30,
        'Equifax Converter',
        'equifax_converter',
        'equifax_converter.q.request',
        'equifax_converter.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        20,
        '5d'
    ),
    (
        31,
        'OKB Converter',
        'okb_converter',
        'okb_converter.q.request',
        'okb_converter.q.request',
        'first_name,last_name,middle_name,birthdate,passport_series,passport_number,system_id',
        20,
        '14d'
    ),
    (
        32,
        'Equifax Payment',
        'equifax_payment',
        'equifax_payment.q.request',
        'equifax_payment.q.request',
        'first_name,middle_name,last_name,birthdate,passport_series,passport_number,system_id,request_version',
        15,
        '5d'
    ),
    (
        33,
        'Equifax FPS',
        'equifax_fps',
        'equifax_fps.q.request',
        'equifax_fps.q.request',
        'first_name,middle_name,last_name,system_id',
        15,
        '14d'
    ),
    (
        34,
        'SBP BIN',
        'sbp_bin',
        'sbp_bin.q.request',
        'sbp_bin.q.request',
        'client_phone',
        10,
        '5d'
    ),
    (
        35,
        'NBKI R2T',
        'nbki_r2t',
        'nbki_r2t.q.request',
        'nbki_r2t.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        15,
        '14d'
    ),
    (
        36,
        'NBKI RUTDF',
        'nbki_rutdf',
        'nbki_rutdf.q.request',
        'nbki_rutdf.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        15,
        '14d'
    ),
    (
        37,
        'PTI BD',
        'pti_bd',
        'pti_bd.q.request',
        'pti_bd.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        41,
        ''
    ),
    (
        38,
        'PTI TZ',
        'pti_tz',
        'pti_tz.q.request',
        'pti_tz.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        41,
        ''
    ),
    (
        39,
        'VK MS',
        'vk_ms',
        'vk_ms.q.request',
        'vk_ms.q.request',
        'client_phone,models',
        20,
        '14d'
    ),
    (
        40,
        'MTC',
        'mtc',
        'mtc.q.request',
        'mtc.q.request',
        'client_phone,models',
        20,
        '14d'
    ),
    (
        41,
        'IP Info',
        'ip_info',
        'ip_info.q.request',
        'ip_info.q.request',
        'client_ip',
        20,
        '30d'
    ),
    (
        42,
        'Equifax Block',
        'equifax_block',
        'equifax_block.q.request',
        'equifax_block.q.request',
        'first_name,middle_name,last_name,birthdate,passport_series,passport_number,system_id',
        15,
        ''
    ),
    (
        43,
        'NBKI Scoring',
        'nbki_scoring',
        'nbki_scoring.q.request',
        'nbki_scoring.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        15,
        '14d'
    ),
    (
        44,
        'Mobile Scoring',
        'mobile_scoring',
        'mobile_scoring.q.request',
        'mobile_scoring.q.request',
        'client_phone',
        10,
        '14d'
    ),
    (
        45,
        'INN BD',
        'inn_bd',
        'inn_bd.q.request',
        'inn_bd.q.request',
        'passport_series,passport_number',
        20,
        '30d'
    ),
    (
        46,
        'Kycmania Verifio',
        'kycmania_verifio',
        'kycmania_verifio.q.request',
        'kycmania_verifio.q.request',
        'vin',
        20,
        '15d'
    ),
    (
        47,
        'Kycmania Auto',
        'kycmania_auto',
        'kycmania_auto.q.request',
        'kycmania_auto.q.request',
        '',
        20,
        '15d'
    ),
    (
        48,
        'Fincert',
        'fincert',
        'fincert.q.request',
        'fincert.q.request',
        '',
        20,
        '15d'
    ),
    (
        49,
        'Fingerprint',
        'fingerprint',
        'fingerprint.q.request',
        'fingerprint.q.request',
        'fingerprint_request_id',
        20,
        '30d'
    ),
    (
        50,
        'Riskseal DCS',
        'riskseal_dcs',
        'riskseal_dcs.q.request',
        'riskseal_dcs.q.request',
        'email,phone',
        20,
        '30d'
    ),
    (
        51,
        'Equifax Open Score',
        'equifax_open_score',
        'equifax_open_score.q.request',
        'equifax_open_score.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        20,
        '14d'
    ),
    (
        52,
        'NBKI Embedding',
        'nbki_embedding',
        'nbki_embedding.q.request',
        'nbki_embedding.q.request',
        'first_name,middle_name,last_name,birthdate,system_id',
        15,
        '14d'
    ),
    (
        53,
        'Unico',
        'unico',
        'unico.q.request',
        'unico.q.request',
        'imageBase64,code',
        20,
        '30d'
    ),
    (
        54,
        'EqvaPay T-Bank',
        'eqvapay_t_bank',
        'eqvapay_t_bank.q.request',
        'eqvapay_t_bank.q.request',
        'eqvapay_id',
        15,
        '1d'
    ),
    (
        55,
        'Equifax Attrs',
        'equifax_attrs',
        'equifax_attrs.q.request',
        'equifax_attrs.q.request',
        'first_name,last_name,middle_name,birthdate,system_id',
        20,
        '14d'
    ),
    (
        56,
        'Gos Auto',
        'gos_auto',
        'gos_auto.q.request',
        'gos_auto.q.request',
        '',
        20,
        ''
    ),
    (
        57,
        'OKB Info',
        'okb_info',
        'okb_info.q.request',
        'okb_info.q.request',
        'first_name,last_name,middle_name,birthdate,passport_series,passport_number,system_id',
        20,
        '14d'
    ),
    (
        58,
        'Credit Circle Short',
        'credit_circle_short',
        'credit_circle_short.q.request',
        'credit_circle_short.q.request',
        'CURP,RFC',
        900,
        '60d'
    )
ON CONFLICT (id) DO NOTHING;

-- Skip if a service with this 'id' already exists
COMMIT;